name: Distributed Load Testing with JMeter (Dockerized)

on:
  push:
    branches:
      - main

jobs:
  load-testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Launch Master Node
        run: |
          docker run -d --name jmeter-master \
            -p 1099:1099 \
            -v $(pwd):/opt/apache-jmeter-5.5/ \
            justb4/jmeter:latest

      - name: Launch Slave Nodes
        run: |
          for i in {1..3}; do
            PORT=$(shuf -i 1025-65535 -n 1)
            docker run -d --name jmeter-slave-$i \
              -p $PORT:1099 \
              -v $(pwd):/opt/apache-jmeter-5.5/ \
              justb4/jmeter:latest
          done

      - name: Check Master Node Status
        run: |
          echo "Master Node Status before start:"
          docker ps -a | grep jmeter-master

      - name: Start Master Node
        run: |
          docker start jmeter-master

      - name: Check Master Node Status after start
        run: |
          echo "Master Node Status after start:"
          docker ps -a | grep jmeter-master

      - name: Run JMeter Test
        run: |
          docker exec jmeter-master jmeter -n -t Demo.jmx -l results.jtl -R 1099

      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: results.jtl

      - name: Stop JMeter Nodes
        run: |
          docker stop jmeter-master
          for i in {1..3}; do
            docker stop jmeter-slave-$i
          done
