name: Distributed Load Testing with JMeter

on: [push]

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        role: [master, slave] # Define roles: one master and one slave
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Download JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.5.tgz -O jmeter.tgz
          tar -xzf jmeter.tgz
          export JMETER_HOME=$(pwd)/apache-jmeter-5.5
          export PATH=$JMETER_HOME/bin:$PATH

      - name: Configure JMeter Slave
        if: matrix.role == 'slave'
        run: |
          echo "Configuring JMeter Slave"
          echo "server.rmi.ssl.disable=true" > $JMETER_HOME/bin/user.properties

      - name: Start JMeter Server (Slave)
        if: matrix.role == 'slave'
        run: |
          echo "Starting JMeter in server mode"
          nohup $JMETER_HOME/bin/jmeter-server > jmeter-server.log 2>&1 &

      - name: Configure JMeter Master
        if: matrix.role == 'master'
        run: |
          echo "Configuring JMeter Master"
          echo "remote_hosts=127.0.0.1" > $JMETER_HOME/bin/user.properties

      - name: Run JMeter Test (Master)
        if: matrix.role == 'master'
        run: |
          echo "Running JMeter Test"
          $JMETER_HOME/bin/jmeter -n -t path/to/your/test-plan.jmx -R127.0.0.1 -l test-results.jtl
          cat test-results.jtl
