
name: Distributed JMeter Load Testing

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  setup-slaves:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        slave: [1, 2, 3, 4]  # Number of slave instances you want to run

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install JMeter
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jre
          wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.5.tgz
          tar -xzf apache-jmeter-5.5.tgz
          export JMETER_HOME=$PWD/apache-jmeter-5.5
          export PATH=$PATH:$JMETER_HOME/bin

      - name: Setup JMeter Slave
        run: |
          echo "Setting up JMeter slave runner-${{ matrix.slave }}"
          nohup jmeter-server -Dserver.rmi.localport=50000 -Dserver_port=1099 > slave-${{ matrix.slave }}.log 2>&1 &

  setup-master:
    runs-on: ubuntu-latest
    needs: setup-slaves

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install JMeter
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jre
          wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.5.tgz
          tar -xzf apache-jmeter-5.5.tgz
          export JMETER_HOME=$PWD/apache-jmeter-5.5
          export PATH=$PATH:$JMETER_HOME/bin

      - name: Configure JMeter Master
        run: |
          echo "Setting up JMeter master runner"
          # Create a properties file to configure the slaves
          echo "remote_hosts=$(for i in {1..4}; do echo runner-$i; done | paste -sd, -)" > $JMETER_HOME/bin/user.properties

  run-load-test:
    runs-on: ubuntu-latest
    needs: setup-master

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run JMeter Load Test
        run: |
          export JMETER_HOME=$PWD/apache-jmeter-5.5
          export PATH=$PATH:$JMETER_HOME/bin
          echo "Running JMeter load test"
          jmeter -n -t Demo.jmx -r

  collect-results:
    runs-on: ubuntu-latest
    needs: run-load-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Collect JMeter Load Test Results
        run: |
          echo "Collecting results"
          mkdir -p results
          mv $JMETER_HOME/bin/*.jtl results/

      - name: Upload JMeter Load Test Results
        uses: actions/upload-artifact@v3
        with:
          name: load-test-results
          path: ./results