name: Distributed Load Test

on:
  push:
    branches:
      - main

jobs:
  start_slave:
    runs-on: ubuntu-latest
    steps:
    - name: Start JMeter Slave
      run: |
        # Start JMeter slave in detached mode
        docker run --name jmeter-slave -d --entrypoint "jmeter-server" justb4/jmeter:latest
    
    - name: Get Slave IP
      id: get_ip
      run: |
        # Retrieve the IP address of the JMeter slave container
        echo "::set-output name=IP::$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' jmeter-slave)"

  start_master:
    runs-on: ubuntu-latest
    needs: start_slave
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Run JMeter Test and Store Results
      run: |
        # Run JMeter master with the retrieved IP of the slave
        docker run --name jmeter-master -v $(pwd):/tests -w /tests justb4/jmeter:latest \
          -n -t /tests/Demo.jmx -R${{ needs.start_slave.outputs.get_ip.IP }} \
          -l /tests/results/results.jtl -e -o /tests/results/report || true

    - name: Commit and Push Results to `results` Branch
      run: |
        # Configure Git with GitHub actions user details
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        
        # Create or switch to the `results` branch
        git checkout -b results || git checkout results
        
        # Add the results directory and commit the changes
        git add results/
        git commit -m "Add JMeter test results"
        
        # Force push the changes to the `results` branch
        git push origin results --force

  analyze_results:
    runs-on: ubuntu-latest
    needs: start_master
    steps:
    - name: Checkout `results` Branch
      uses: actions/checkout@v2
      with:
        ref: results

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: View JMeter Report
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./results/report
