name: Distributed Load Testing with JMeter

on: [push]

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [1, 2] # Define two nodes: 1 for master and 1 for slave
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Download JMeter
        run: |
          curl -L https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.5.tgz > jmeter.tgz
          tar -xzf jmeter.tgz
          export JMETER_HOME=$(pwd)/apache-jmeter-5.5
          export PATH=$JMETER_HOME/bin:$PATH

      - name: Configure JMeter Slave
        if: matrix.node == 2
        run: |
          echo "Configuring JMeter Slave"
          echo "slave.runs-on=ubuntu-latest" > user.properties

      - name: Start JMeter Server (Slave)
        if: matrix.node == 2
        run: |
          echo "Starting JMeter in server mode"
          nohup jmeter-server &

      - name: Configure JMeter Master
        if: matrix.node == 1
        run: |
          echo "Configuring JMeter Master"
          echo "remote_hosts=127.0.0.1" > $JMETER_HOME/bin/user.properties
          echo "client.runs-on=ubuntu-latest" >> $JMETER_HOME/bin/user.properties

      - name: Run JMeter Test (Master)
        if: matrix.node == 1
        run: |
          echo "Running JMeter Test"
          jmeter -n -t Demo.jmx -R127.0.0.1 -l test-results.jtl
          cat test-results.jtl
