name: Distributed Load Testing with JMeter

on:
  push:
    branches:
      - main

jobs:
  load-testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install JMeter
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk
          curl -L https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-latest.zip -o jmeter.zip
          unzip jmeter.zip
          rm jmeter.zip
          JMETER_VERSION=$(unzip -c jmeter.zip | grep "apache-jmeter-" | cut -d" " -f6 | cut -d"/" -f2)
          echo "JMeter version: $JMETER_VERSION"
          cd apache-jmeter-$JMETER_VERSION

      - name: Configure JMeter Master
        run: |
         ./bin/jmeter -n -t test.jmx -l log.jtl -R${{ github.run_id }}-master

      - name: Launch JMeter Slaves
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ github.run_id }}-slave-1
          username: ubuntu
          password: ${{ secrets.UBUNTU_PASSWORD }}
          script: |
            cd apache-jmeter-${JMETER_VERSION}
             ./bin/jmeter -n -t test.jmx -l log.jtl -R${{ github.run_id }}-slave-1

      - name: Launch JMeter Slaves
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ github.run_id }}-slave-2
          username: ubuntu
          password: ${{ secrets.UBUNTU_PASSWORD }}
          script: |
            cd apache-jmeter-${JMETER_VERSION}
              ./bin/jmeter -n -t test.jmx -l log.jtl -R${{ github.run_id }}-slave-2

      - name: Wait for Slaves to Finish
        run: |
          sleep 300

      - name: Stop JMeter Master
        run: |
          cd apache-jmeter-${JMETER_VERSION}
          ./bin/jmeter -n -t test.jmx -l log.jtl -s

      - name: Collect Results
        run: |
          mkdir results
          cp log.jtl results/
          tar -czf results.tar.gz results

      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: results.tar.gz
