name: Distributed Load Test

on:
  push:
    branches:
      - main

jobs:
  start_slave:
    runs-on: ubuntu-latest
    container:
      image: justb4/jmeter:latest
      options: --entrypoint "jmeter-server"
    steps:
    - name: Get Slave IP
      id: get_ip
      run: echo "::set-output name=IP::$(hostname -I | awk '{print $1}')"

  start_master:
    runs-on: ubuntu-latest
    needs: start_slave
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '11'
      
    - name: Prepare Results Directory
      run: mkdir -p results

    - name: Start JMeter Master
      run: |
        # Retrieve the IP address of the JMeter slave
        SLAVE_IP=$(echo "${{ needs.start_slave.outputs.get_ip.IP }}")
        
        # Run JMeter master with the retrieved IP of the slave
        docker run --name jmeter-master -v $(pwd):/tests -w /tests justb4/jmeter:latest \
          -n -t /tests/Demo.jmx -R"${SLAVE_IP}" \
          -l /tests/results/results.jtl -e -o /tests/results/report || true

    - name: List Results Directory for Debugging
      run: ls -l results

    - name: Commit and Push Results to `results` Branch
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git checkout -b results || git checkout results
        git add results/
        git commit -m "Add JMeter test results"
        git push origin results --force

  analyze_results:
    runs-on: ubuntu-latest
    needs: start_master
    steps:
    - name: Checkout `results` Branch
      uses: actions/checkout@v2
      with:
        ref: results

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Download JMeter results
      uses: actions/download-artifact@v2
      with:
        name: jmeter-results
        path: ./results
        
    - name: Upload JMeter report as artifact
      uses: actions/upload-artifact@v2
      with:
        name: jmeter-report
        path: ./results/report
        
    - name: View JMeter report
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./results/report
